### ISSUE TITLE
file terminate by empty line (generaly)

### ISSUE THREAD

**Issue by GwenaelPellenMatelli** [kasik96/VSCode-PHP-Format#1]
Hello, thank you for this work.

Formatting deletes the last empty line in the file.

line 1: ....\n
line 2: ....\n
line 3: ....\n
line 4:

Text files terminate generaly by an empty line.

**Comment by kasik96** [comment]
Hi, thanks for this report. I will look at it. :+1:

**Comment by kasik96** [comment]
Ok, i look at it. If i get your report right, i think thats not problem, thats part of Indentation algorithm, to eliminate empty lines. If you make 10 empty lines on end of file, indentation will terminate all of it.

**Comment by kasik96** [comment]
Fixed in new 1.1.0 Version
