### ISSUE TITLE
Stopped working after update

### ISSUE THREAD

**Issue by R3D0** [kasik96/VSCode-PHP-Format#12]
Hello,

~~I have been using your extension for some time now, but after I updated it a few days ago, it no longer works.~~
~~I tested it with the following code: ~~
~~`$sql -> execute();`~~
~~Which is usually altered to:~~
~~`$sql->execute();` (no spaces around '->')~~
~~I have tried both the shift+alt+f shortcut, as well as the command from the menu. Neither affects any php file.~~

~~Both commands work as they should in any other file type.~~

~~I hope this is something easy to fix, as this extension has saved me much time keeping everything neat and orderly!~~

EDIT:

Ok, so upon further testing I found the problem. The php page must start with
`<?php`
*NOT*
`<?PHP`

This is somewhat an odd problem to have...

Thanks

**Comment by kasik96** [comment]
Fixed :+1:
