### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by J-Siu** [kasik96/VSCode-PHP-Format#13]
I start using vscode less than a month. Please forgive me if this is a dump question.

OS: OS X 10.11.3
VSCode: 0.10.6
Download via git clone
Extension path: ~/.vscode/extensions/VSCode-PHP-Format

I restarted VSCode, open php files, but do not see "Format Code" on the right click menu.

**Comment by J-Siu** [comment]
Issue found. Missing js-beautify.

**Solution**(need to install npm first)

Inside ~/.vscode/extensions/VSCode-PHP-Format, run

> npm install

It will pull in js-beautify. Then restart VSCode.

**Comment by J-Siu** [comment]
Suggest to update README for installation instruction.

**Comment by kasik96** [comment]
Hi. Thats very strange. VS Code, install all dependencies by self. What OS do you use and what version of VS?

**Comment by J-Siu** [comment]
OS: OS X 10.11.3
VSCode: 0.10.6
I download the plugin using git clone. Not through "extension install" inside VSCode, as I don't see it there.

**Comment by kasik96** [comment]
Thats problem, i dont support manual installation. You must install extension trought Market. Just type "PHP Format" in finder of extension in VS Code :).

**Comment by J-Siu** [comment]
As I said, your plugin is not showing up in the Market / Ext Install. That is the first place I try. It only show up AFTER I download it. At the point there is only 2 buttons to click: "README" and "X"(uninstall).
