### ISSUE TITLE
php program was not found

### ISSUE THREAD

**Issue by lsahidin** [kasik96/VSCode-PHP-Format#15]
Hi, thank you for your PHP Format it's a great!!
I'm new with VSCode, but I wanna try. after install the PHP Format plugin I have a problem with message "Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'". when I try to check this plugin is already installed or not, it was not yet installed. Could you help me to solve the problem? Thanks.

**Comment by kasik96** [comment]
That problem of PHP validator in VS Code. This has nothing to do with PHP Format extension.
