### ISSUE TITLE
Indent switch not work

### ISSUE THREAD

**Issue by DzeryCZ** [kasik96/VSCode-PHP-Format#2]
Hello,

Your plugin is great, but I've noticed, that indent of switch doesn't work.
It looks like

    <?php
    switch($test){
        case '5':
        //sth
        break;
        default:
        //sth
    }
But it should looks like:

    <?php
    switch($test){
        case '5':
            //sth
            break;
        default:
            //sth
    }

Thank you. :)

**Comment by kasik96** [comment]
Update 1.0.2 fixed this. Thanks for you report :+1:

**Comment by DzeryCZ** [comment]
Great! Many thanks  :+1:
