### ISSUE TITLE
formatter not working

### ISSUE THREAD

**Issue by gandesc** [kasik96/VSCode-PHP-Format#25]
I had VS Code installed, with no plugins.

Installed the formatter through VS Code, restarted VSC, wrote some php code with wacky indentation, spaces etc, selected it, used keyboard shortcut, nothing happens.
with text still selected, right click -> format, nothing happens.

I don't seem to have any VSC errors, have no other plugins. How can I figure out what's wrong?
Thanks!

Windows 8.1, VSC 0.10.10

**Comment by kasik96** [comment]
Did you install it trought the VS Code Extension Galery?

**Comment by gandesc** [comment]
Hi,

I've installed it through VSC: ctrl+P -> extensions -> install extension -> find it, select it, install

**Comment by kasik96** [comment]
I cant reproduce your problem, sorry but i cant do more. Maybe problem of W8. Only Mac OS X, Linux and W10. Thanks.
