### ISSUE TITLE
Formatting in just one line

### ISSUE THREAD

**Issue by gmsantos** [kasik96/VSCode-PHP-Format#3]
I've got a strange behavior, on both Windows 10 and Ubuntu.

Starting with this file and formatting:

![capture](https://cloud.githubusercontent.com/assets/1991286/12133706/04af9e8a-b40f-11e5-971a-972d7f8aa139.PNG)

It ended up like this:

![capture1](https://cloud.githubusercontent.com/assets/1991286/12133709/0c9a1382-b40f-11e5-88b2-2ebe02c3f024.PNG)

Using PHP Format 1.1.0
VS Code 0.10.6 Win and Ubuntu

**Comment by kasik96** [comment]
Hi, i see, its becouse you didnt end php tag with ?> but still its bug, i
fix it soon. Thanks :)

**Comment by kasik96** [comment]
Fixed in 1.1.1 :+1:
