### ISSUE TITLE
Quoted string from array leads to undefined index error

### ISSUE THREAD

**Issue by pvredeveld** [kasik96/VSCode-PHP-Format#4]
<?php
$options = array("one"=>"quoted value"); 
$str = "Text with '{$options["one"]}' from array.\n";
echo $str;
?>

will result in : 

<?php 
$options = array("one" => "quoted value");
$str = "Text with '{$options["
one "]}' from array.\n";
echo $str;
?>

with is a syntax error:

Notice: Undefined index: 
one  in .\bug.php on line 4
Call Stack:
    0.0002     123808   1. {main}() .\bug.php:0
Text with '' from array.

**Comment by kasik96** [comment]
1.2.0 is out with fix.

**Comment by pvredeveld** [comment]
Hi, this bug is not fixed in 1.2.0. In my example $options is a variable with an arbitrary name. 
For example $str = "Text with '{$rs["one"]}' from array.\n"; still is malformed in
$str = "Text with '{$rs["
one"]}' from array.\n";
