### ISSUE TITLE
Formatting PHTML files

### ISSUE THREAD

**Issue by carathorys** [kasik96/VSCode-PHP-Format#9]
Hi! 

I've tried your VSCode plugin, it's very useful. 
I use Zend Framework 2, and when I try to format my PHTML files, the plugin host just exit with the following error message: 
> Plugin host terminated unexpectedly. Please restart VSCode to recover.

In my PHTML there is a few PHP blocks, mostly with echos, or `<?=$var?>` tags .
I'm doing somthing wrong, or there is a bug in the plugin? 

Here is the stack:
> Plugin host terminated unexpectedly. Please restart VSCode to recover.
```javascript
e.doShow @ workbench.main.js:63
e.show @ workbench.main.js:63
(anonymous function) @ workbench.main.js:67
emitTwo @ events.js:87
emit @ events.js:172
ChildProcess._handle.onexit @ internal/child_process.js:200
```

> Plugin host terminated unexpectedly. Code:  3  Signal:  null
```javascript
(anonymous function) @ workbench.main.js:67
emitTwo @ events.js:87
emit @ events.js:172
ChildProcess._handle.onexit @ internal/child_process.js:200
```

**Comment by kasik96** [comment]
Sorry, not have any plane to add this.
